### ISSUE TITLE
Graue Notenfelder

### ISSUE THREAD

**Issue by FPfotenhauer** [FPfotenhauer/Zeugnisse-NRW#11]
Die Notenfelder sind je nachdem, welchen Laserdrucker man hat manchmal dunkel, manchmal hell.
Man könnte den Schulen über die INI-Datei die Möglichkeit geben, den Grauton anzupassen.

Ist ein Vorschlag zur Diskussion, wenn man sonst keine Probleme mehr hat....

**Comment by EwaldReinhardt** [comment]
Ich denke, dass das sinnvoll ist. Wir hatten das Problem bei uns auch als die HP-Drucker durch Kyoceradrucker getauscht wurden.

**Comment by FPfotenhauer** [comment]
Dann sollten wir darüber reden, wenn die anderen Issues abgearbeitet sind. Ich würde das als Zusatz-Option sehen, bei der Michael Plümper auch sagen muss, ob er uns das in die INI-Datei einbauen kann.
Vielleicht kann man das jetzt schon mal bedenken und wir setzen es dann um, wenn allles andere fertig ist.

**Comment by M-Plu** [comment]
Das geht sicherlich, ist aber für alle mit einer größeren Anpassung verbunden, weil jeder einzelne Subreport mit einem Notenfeld in der Programmierung angefasst werden muss. Dagegen ist die Anpassung der INI schnell erledigt.

**Comment by FPfotenhauer** [comment]
Bitte bedenke das schon mal mit. Wir machen das aber erst, wenn alles andere erledigt ist und wir sonst keine Sorgen mehr haben.

**Comment by M-Plu** [comment]
Habe die Option jetzt in die INI eingebaut und in einem ersten Zeugnis mal umgesetzt. Das dauert ungefähr 10 Minuten pro Zeugnis. Dabei kann man dann auch gleich einige Fehler in der Namesvergabe bei den Notenfeldern korrigieren.
