### ISSUE TITLE
Fehlende Abfrage bei fehlender INI

### ISSUE THREAD

**Issue by mueller-falko** [FPfotenhauer/Zeugnisse-NRW#12]
Wenn man die Gesamtschulzeugnisse aufruft und keine INI-Datei vorhanden ist, wird man nicht nach dem WP-Beginn gefragt.

**Comment by M-Plu** [comment]
Sollte mit der nächsten Umsetzung des INI-Einlesens behoben sein. 

@mueller-falko  Wenn ich das nächste Formular zusende, bitte man Testen.
