### ISSUE TITLE
INI Einstellungen für Unicode und EmbedFonts bei PDF Druck

### ISSUE THREAD

**Issue by M-Plu** [FPfotenhauer/Zeugnisse-NRW#13]
Der Wunsch nach der Implementierung der Einstellungen in der INI ist halb umgesetzt. UNicode kann man per INI nun ein- und ausschalten.

Bei den EmbedFonts ist es mir bisher nicht gelungen, den Aufruf in RAP hinzubekommen. Nachdem ich nun alle Dokus von Digital Metaphores durch habe, meine Frage:

Wie ist der folgende Aufruf korrekt in RAP zu fomulieren (denn alle aufgeführten Varianten scheitern).

Report.PDFSettings.EmbedFontOptions.efAllFonts := true;
Report.PDFSettings.EmbedFontOptions['efAllFonts'] := true;

**Comment by FPfotenhauer** [comment]
Ich habe Herrn Richter angeschrieben.
Wenn wir dafür keine Lösung bekommen, dann lassen wir es bei "unicode".
Embedded Fonts brauchen wir bei Calibri ja nicht so dringend....

**Comment by mueller-falko** [comment]
Ich habe noch eine Frage zu der Idee eines Globalen Teils in der INI: soll dass dann so laufen, dass ich alle Parameter, die ich für alle Zeugnisse setzen möchte, in diese Globale Sektion kommen (z.B. auch "MitRand" oä) und ich dann in die Abschnitte der einzelnen Anlagen nur die spezifischen Werte eintrage, oder ist es so gedacht, dass bestimmte Parameter nur in der Globalen Sektion erscheinen und andere nur in den Teilen der Anlagen? Wie entscheiden wir denn dann, welche Parameter wohin kommen?

**Comment by M-Plu** [comment]
Ich habe das mit dem globalen Teil noch mal überdacht. Ich denke, wir sollten einfach den bisherigen Ansatz mit einem Teil pro Anlage beibehalten. Das ist flexibler und sogar leichter einzulesen.

**Comment by mueller-falko** [comment]
Finde ich gut.
