### ISSUE TITLE
Seiten 1 und 4 bei Abgangs-/Abschlusszeugnissen ausblenden

### ISSUE THREAD

**Issue by M-Plu** [FPfotenhauer/Zeugnisse-NRW#14]
Im [Forum](https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=16&t=1458&sid=c7b238689db07a76d3c42353a5843521) wurde vorgeschlagen, dass man bei den Abgangs-/Abschlusszeugnissen evtl. die Seiten 1 und 4 Ausblenden können sollte. 

Ich werde mal eine Option in der INI testen. Allerdings werde ich erst Mitte nächster Woche dazu kommen.

**Comment by mueller-falko** [comment]
Wenn’s funktioniert, eine gute Idee.
