### ISSUE TITLE
Alle Vorname

### ISSUE THREAD

**Issue by FPfotenhauer** [FPfotenhauer/Zeugnisse-NRW#3]
Ein Vorschlag war, das Feld "Weitere Virnamen" für "Alle Vornamen" zu verwenden und das Verhalten der Sek1-zeugnisse damit dem Verhalten der Abitur- und GS-Zeugnisse anzupassen.

Problematisch ist dann der Name des Datenfeldes in der Reporting, wenn man das in AlleVornamen umbenennt, dann sind alte Reports nicht mehr kompatibel.

**Comment by M-Plu** [comment]
Mein Vorschlag dazu wäre, dass wir in der INI-Datei eine Option schaffen, welche festlegt, welches Feld für den Zeugnisdruck genutzt wird. Dabei wird darauf hingewiesen, dass das Feld "Weitere Vornamen" dann interpretiert wird wie ALLE Vornamen.
Ich habe das bei den GY-Zeugnissen mal gemacht.
