### ISSUE TITLE
Doppelter WP-Subreport in Zeugnissen des HS-Bereichs der RS

### ISSUE THREAD

**Issue by mueller-falko** [FPfotenhauer/Zeugnisse-NRW#30]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=16&t=2202&p=12838#p12838

**Comment by FPfotenhauer** [comment]
@mueller-falko : Du hast Recht! Der untere WP-Bereich ist aus dem RS-Paket mitkopiert worden! Der hat auf einem HS-Zeugnis dort aber gar nichts zu suchen!

Kannst du das einchecken?

**Comment by mueller-falko** [comment]
Erledigt.
