### ISSUE TITLE
PDF Druck schlechte Bilder

### ISSUE THREAD

**Issue by FPfotenhauer** [FPfotenhauer/Zeugnisse-NRW#6]
In allen Zeugnissen sollte die ImageCompression auf 0 gesetzt werden.

**Comment by FPfotenhauer** [comment]
In allen Zeugnissen sollten diese Einstellungen angepasst werden:

![2020-01-21_115327](https://user-images.githubusercontent.com/34127980/72799145-d8be1500-3c44-11ea-9207-7f842233a8b1.jpg)

**Comment by FPfotenhauer** [comment]
Die UNI-Code-Einstellung beachten!!!

**Comment by FPfotenhauer** [comment]
Außerdem EmbeddedFonts!

**Comment by FPfotenhauer** [comment]
Anregung eines Fachberaters:
 - Image Compression Level auf 90 % setzen
 - ScaleImages auf False setzen
 - PDF/A auf True setzen.

**Comment by M-Plu** [comment]
Wie Falko und ich in der letzten E-Mail geschrieben haben, führen Unicode und EmbeddedFonts zu sehr großen Dateien. Die anderen Optionen sind unkritisch. Daher wäre die Frage, ob man die beiden ersten Optionen unbedingt benötigt.

**Comment by M-Plu** [comment]
Bzgl. Unicode-Unterstützung und evtl. auch Font-Einbettung könnte man natürlich auch mal über eine „globale“ INI-Sektion nachdecken, die entsprechend dokumentiert wird. 

Das muss ich aber mal testen, inwiefern diese Option in der Programmierung gesetzt werden können, und ob sie dann auch greifen.

**Comment by FPfotenhauer** [comment]
Ok. dann lassen wir Embedded-Fonts-All und Uni-Code zunächst einmal raus.
Michael? Kannst du dann die Unicode-option einmal in der Dokumentation ansprechen?

![2020-02-16_115724](https://user-images.githubusercontent.com/34127980/74603428-b7b9da00-50b3-11ea-9f90-935c14503f2f.jpg)

**Comment by M-Plu** [comment]
Ich würde zunächst mal versuchen, die INI Sektion zu realisieren. Wenn das funktioniert, dann muss kein Benutzer mehr im Report selbst Hand anlegen. Sollte das nicht funktionieren, dann kann man das "Bearbeiten im Report dokumentieren".

**Comment by mueller-falko** [comment]
Werde mich gleich mal ans GE Paket machen, Kann gerne auch noch andere übernehmen.

**Comment by M-Plu** [comment]
Hallo Falko, wenn du schon mal die "festen" Eigenschaften setzen kannst, dann werde ich mich mal die nächsten Tage an die INI setzen für Unicode und Fonts. Der Code muss dann noch kopiert werden.

**Comment by FPfotenhauer** [comment]
Ist im SK-Paket auch umgesetzt.

**Comment by mueller-falko** [comment]
Habe GE, GY, HS und RS erledigt. GymOb machen wir, wenn wir die neu aufsetzen, denke ich.
Was ist mit den Inklusionszeugnissen?

**Comment by FPfotenhauer** [comment]
Die Inklusionszeugnisse sind nicht von uns.
Das können wir so lassen, ich hatte die nur zur Vollständigkeit im Git.
Ich stelle die Paket diese Woche online!

**Comment by M-Plu** [comment]
Warum ist das Issue schon geschlossen. Die INI Umsetzung fehlt noch für Unicode und EmbedFonts.
