### ISSUE TITLE
Förderschwerpunkt-Bemerkungen

### ISSUE THREAD

**Issue by beaumart** [FPfotenhauer/Zeugnisse-NRW#7]
Wir hatten im Juli letzten Jahres darüber diskutiert, wie die FS-Bemerkung aufs Zeugnis kommen. Da sollten wir vielleicht abschließend drüber sprechen.

**Comment by FPfotenhauer** [comment]
Eine Umstellung auf das neue Feld "individuelle FS-Bemerkung" wäre auf jeden Fall sinnvoll!

**Comment by FPfotenhauer** [comment]
Außerdem ist es m.E. sinnvoll die Programmierung aus den GS-Zeugnisse einzubauen.
Die führt dazu, das bei Katalogeinträgen die Abkürzungen esetzt werden:

![2020-01-26_140310](https://user-images.githubusercontent.com/34127980/73135644-b8c39280-4044-11ea-823e-d37a90e2aca1.jpg)

**Comment by FPfotenhauer** [comment]
Ich werde auch bei Ribeka nachfragen, ob es Floskel Ersetzungen geben kann für FÖS und Bildungsgang.

**Comment by M-Plu** [comment]
Ich denke, wir sollten wie an anderen Stellen auch, wegkommen von Textersetzungen. Stattdessen wären Felder in SchILD zur Eingabe sinnvoll, wo der User den Text definiert. Wenn er dabei durch Floskeln unterstützt werden kann, wäre das natürlich gut.

**Comment by FPfotenhauer** [comment]
![2020-02-19_121916](https://user-images.githubusercontent.com/34127980/74829803-1e3c3380-5312-11ea-89d7-73adfd5981c2.jpg)

Dann wäre eine Umstellung auf das neue Feld sinnvoll.
Zu diskutieren bleibt, ob unser automatischer Satz bleibt?
Oder ob wir generell dazu übergehen, einfach nur das neue Memo-Feld auszulesen???

**Comment by M-Plu** [comment]
Wenn Felder da sind, sollte man die nutzen. Die sollten natürlich Floskeln unterstützen. 
Da es bei der Versetzung zwei Felder gibt, würde ich sagen, dass der individuelle Versetzungsvermerk geprüft wird. Ist der leer, so erscheint der bisher im Zeugnis generierte Text.

**Comment by FPfotenhauer** [comment]
Da bin ich genau der selben Meinung!

**Comment by mueller-falko** [comment]
Vielleicht ist das ja eine ketzerische Frage, aber warum wird der Text überhaupt im Zeugnisformular erzeugt? Es gibt doch auch andere Bemerkungen, die verpflichtend auf bestimmte Zeugnisse müssen, die nicht im Formular erzeugt werden, sondern in der Verantwortung der Schulen liegen. Warum verfahren wir mit der Förderbemerkung nicht genauso? Denn bisher hat diese Automatik sowohl inhaltlich als auch programmtechnisch eher Probleme verursacht.

**Comment by FPfotenhauer** [comment]
Wenn die Formulare auf das neue Memo-Feld umgestellt sind, dann wäre die Automatik ja auch überflüssig. Dann würde man das mit Floskeln regeln können.

**Comment by FPfotenhauer** [comment]
Sorry, wollt enicht closen...

**Comment by M-Plu** [comment]
Die GYM-Zeugnisse enthalten nun nur noch das Memo.

**WICHTIG: Dann müssen alle Schulen aber vorher auf die aktuelle SchILD-Version aktualisiert haben. Sonst gibt es hier Fehler, weil die Zeugnisse dann auf nciht vorhandene Fehler zugreifen. Daher bitte das alte Packet gut sichern und bereitstellen.**

**Comment by beaumart** [comment]
Ich bin auch für die Floskel-Regelung. Das ist am variabelsten. Auf jeden Fall sollte keine Mischung aus berechneten Texten und selbst hinzugefügten Sätzen ob nun selbst getippt oder über Floskeln, vermeiden.

**Comment by FPfotenhauer** [comment]
Ich denke ein Update bis zum Sommer sollte man erwarten können.
Die Datenquelle heißt Lernabschitte > ASVSek_1.
Dort sieht man die Memo-Felder.

![2020-02-26_123820](https://user-images.githubusercontent.com/34127980/75341706-489f6b00-5895-11ea-8293-5b7ccff8de98.jpg)

**Comment by FPfotenhauer** [comment]
Ich habe gerade mit Michael gesprochen.
Wir werden den Zeugnissen dann die Versionsnummer 8.1 geben.
Dann werden die älteren Formulare auchnicht überschrieben.

Ich sende nachher ein Paket zum testen für alle.
Darin kann man sich alle Änderungen ansehen und dann in den anderen Paketen "nachmachen".
